spring.config.import=optional:file:.env[.properties]
server.port=8083

app.upload-dir=/opt/mavunohub/uploads

spring.application.name=e-commerce

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mavuno_hub
spring.datasource.username=brian
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false #true for development/debugging

# Multipart File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# JWT Configuration
jwt.secret.key=dnlavnlkvanvkanlanblkanblkanalknaklnakldnvaknalkvanklsnvkanvlksndbad vncx valkdgslkn.laf;amvvjdbnkjdsb zlkdfjzlk zm zlknvlzk zldmfkv zm vkjzv
jwt.access.token.expiration=900000
jwt.refresh.token.expiration=604800000
jwt.issuer=authentication-service
jwt.audience=authentication-client

# set logging level to Debug
logging.level.org.springframework.security=DEBUG

# Paystack
paystack.secret=sk_test_59e2cd9d9f1a13d49ffbb74905d9207b8940d996
paystack.base-url=https://api.paystack.co


